### ISSUE TITLE
linux上的疑问

### ISSUE THREAD

**Issue by TalkIsCheapGiveMeMoney** [SW-Fantastic/cpp-presets#2]
编译完成得到的Jar 如果需要在linux上使用是不是还需要再linux上进行mvn package

**Comment by SW-Fantastic** [comment]
通常情况下，是的，我目前没有为linux系统提供适配，你可能需要手动增加一些linux的header之类的东西，如果你在使用Windows，你可以在源码的resource目录看到我预编译的动态库，有的时候macos的也有，目前我尚未对这些类库适配linux系统，但是过一段时间也许会添加对linux的支持。

**Comment by SW-Fantastic** [comment]
是否支持一个系统，你可以检查resource里面是否存在该系统的动态链接库，目前尚未支持linux，但是linux的支持在我的计划中，编译一个jar文件的时候，如果运行它的操作系统需要的动态库存在于resource里面，那么你无需进行编译，就可以拿着之前编译好的jar直接使用，如果该操作系统尚不支持，你又需要，你可以手动fork本项目，此时你应当自行编译，并且按照javacpp的方式把动态库放入resource里面并且为你的操作系统打包，此时，你的得到的jar包将会支持所有包含在resource中的操作系统类型。

**Comment by SW-Fantastic** [comment]
本项目增加了部分项目的Linux支持，并且直接提供Release版本，请使用其中的local-repository，也就是本地仓库进行使用，本地仓库可以避免直接添加Jar可能出现的类库缺失等麻烦问题，添加后可以按照普通的maven组件依赖和使用。
